name: mirror

on:
  schedule:
    # Run every sunday at 1:27 UTC
    - cron: '27 1 * * SUN'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      -
        name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: alpine
        uses: efrecon/gh-action-docker-mirror@feature/multi-platform
        with:
          image: alpine
          minver: 3.17
          registry: ghcr.io/efrecon

